<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-27T19:09:17 IST" name="Default suite" finished-at="2022-09-27T19:09:50 IST" duration-ms="32328">
    <groups>
    </groups>
    <test started-at="2022-09-27T19:09:17 IST" name="Default test" finished-at="2022-09-27T19:09:50 IST" duration-ms="32328">
      <class name="com.vtechsolution01.orangehrm.testcase.Login_TC02">
        <test-method is-config="true" signature="init()[pri:0, instance:com.vtechsolution01.orangehrm.testcase.Login_TC02@671a5887]" started-at="2022-09-27T19:09:15 IST" name="init" finished-at="2022-09-27T19:09:17 IST" duration-ms="2148" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.vtechsolution01.orangehrm.testcase.Login_TC02@671a5887]" started-at="2022-09-27T19:09:17 IST" name="setUp" finished-at="2022-09-27T19:09:47 IST" duration-ms="29930" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTest()[pri:0, instance:com.vtechsolution01.orangehrm.testcase.Login_TC02@671a5887]" started-at="2022-09-27T19:09:47 IST" name="loginTest" finished-at="2022-09-27T19:09:48 IST" duration-ms="567" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.vtechsolution01.orangehrm.testcase.Login_TC02.loginTest(Login_TC02.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="TearDown(org.testng.ITestResult)[pri:0, instance:com.vtechsolution01.orangehrm.testcase.Login_TC02@671a5887]" started-at="2022-09-27T19:09:48 IST" name="TearDown" finished-at="2022-09-27T19:09:49 IST" duration-ms="1337" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=Login_TC02.loginTest()[pri:0, instance:com.vtechsolution01.orangehrm.testcase.Login_TC02@671a5887] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="ExtendFlush()[pri:0, instance:com.vtechsolution01.orangehrm.testcase.Login_TC02@671a5887]" started-at="2022-09-27T19:09:49 IST" name="ExtendFlush" finished-at="2022-09-27T19:09:50 IST" duration-ms="434" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ExtendFlush -->
      </class> <!-- com.vtechsolution01.orangehrm.testcase.Login_TC02 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
